import { Metadata } from 'next';
import React from 'react';

import AdminSidebar from '@/components/layout/AdminSidebar/AdminSidebar';

export const metadata: Metadata = {
  title: 'BAYDA: sign-in',
  description: 'Generated by create next app',
};

export default function AdminLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-[2fr_10fr] mx-auto px-4 items-start pt-16 md:container md:mx-auto">
      <AdminSidebar />
      {children}
    </div>
  );
}
