import { Metadata } from 'next';
import React from 'react';

import { Header } from '@/components/layout/Header/Header';

export const metadata: Metadata = {
  title: 'BAYDA: sign-in',
  description: 'Generated by create next app',
};

export default function MainLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
