import { Metadata } from 'next';
import Image from 'next/image';
import React from 'react';

export const metadata: Metadata = {
  title: 'BAYDA: sign-in',
  description: 'Generated by create next app',
};

export default function AuthLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="grid grid-cols-1 h-screen md:grid-cols-2">
      {children}
      <div className="hidden md:block overflow-hidden">
        <Image
          src="/images/login-banner.jpg"
          alt="Login Art"
          width={2048}
          height={1344}
          priority
          className="h-[100vh] w-full object-cover"
        />
      </div>
    </div>
  );
}
