import { Metadata } from 'next';
import React from 'react';

import ProfileSidebar from '@/components/layout/ProfileSidebar.tsx/ProfileSidebar';

export const metadata: Metadata = {
  title: 'BAYDA: sign-in',
  description: 'Generated by create next app',
};

export default function ProfileLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-[1fr_4fr] container mx-auto px-4 items-start pt-64">
      <ProfileSidebar />
      <main>{children}</main>
    </div>
  );
}
